Collectd tests failed with... (#1282)
java.net.SocketException: Can't assign requested address
...appears to happen when an IPv6 interface or address is used.
This commit makes test run with -Djava.net.preferIPv4Stack=true